import type { Manifest } from "@slack/web-api/dist/types/request/manifest"

type BotScope = (((Manifest['oauth_config'] & {})['scopes'] & {})['bot'] & {})[number]

export const ID = {
	runWorkflow: 'run_workflow_80b152f4-c481-4781-8c34-edb5f8488c9f'
}

export const WORKFLOW_APP_SCOPES: BotScope[] = [
	'app_mentions:read',
	'bookmarks:read',
	'bookmarks:write',
	'calls:read',
	'calls:write',
	'channels:history',
	'channels:join',
	'channels:manage',
	'channels:read',
	'channels:write.invites',
	'channels:write.topic',
	'chat:write',
	'chat:write.customize',
	'chat:write.public',
	'commands',
	'dnd:read',
	'emoji:read',
	'files:read',
	'files:write',
	'groups:history',
	'groups:read',
	'groups:write',
	'groups:write.invites',
	'groups:write.topic',
	'im:history',
	'im:read',
	'im:write',
	'links.embed:write',
	'links:read',
	'links:write',
	'metadata.message:read',
	'mpim:history',
	'mpim:read',
	'mpim:write',
	'mpim:write.topic',
	'pins:read',
	'pins:write',
	'reactions:read',
	'reactions:write',
	'reminders:read',
	'reminders:write',
	'team.billing:read',
	'team.preferences:read',
	'team:read',
	'usergroups:read',
	'usergroups:write',
	'users.profile:read',
	'users:read',
	'users:read.email',
	'users:write',

	// bolt doesn't recognize these smh
	'canvases:read' as BotScope,
	'canvases:write' as BotScope,
	'im:write.topic' as BotScope,
	'lists:read' as BotScope,
	'lists:write' as BotScope,
	'search:read.files' as BotScope,
	'search:read.im' as BotScope,
	'search:read.mpim' as BotScope,
	'search:read.private' as BotScope,
	'search:read.public' as BotScope,
	'search:read.users' as BotScope
]
